"""empty message

Revision ID: 27a10d3d48f5
Revises: 682182db9f7d
Create Date: 2022-07-14 09:40:36.738919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a10d3d48f5'
down_revision = '682182db9f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('category_name', sa.String(length=180), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'category_name')
    # ### end Alembic commands ###
