"""empty message

Revision ID: 682182db9f7d
Revises: c56ff1886a33
Create Date: 2022-07-14 08:34:32.390896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682182db9f7d'
down_revision = 'c56ff1886a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('recipe_url', sa.String(length=250), nullable=False))
    op.add_column('favorite', sa.Column('recipe_title', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'recipe_title')
    op.drop_column('favorite', 'recipe_url')
    # ### end Alembic commands ###
